# Defines the services, networks, and volumes for the application.
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./app:/app/app # Mount local app directory for live reloading

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${DB_PASSWORD}" # Use the password from .env file
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: