"""fix_database_schema

Revision ID: 53fcc16c5bbf
Revises: d610b86fe77a
Create Date: 2025-11-23 20:26:43.373221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53fcc16c5bbf'
down_revision: Union[str, None] = 'd610b86fe77a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
