"""add_repo_url_to_projects

Revision ID: d610b86fe77a
Revises: 
Create Date: 2025-11-23 20:24:02.048637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd610b86fe77a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog_posts', 'tags',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('blog_posts', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('blog_posts', 'views',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('blog_posts', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_blog_posts_published'), 'blog_posts', ['published'], unique=False)
    op.create_index(op.f('ix_blog_posts_title'), 'blog_posts', ['title'], unique=False)
    op.drop_constraint('blog_posts_author_id_fkey', 'blog_posts', type_='foreignkey')
    op.create_foreign_key(None, 'blog_posts', 'users', ['author_id'], ['id'])
    op.drop_column('blog_posts', 'image_url')
    op.alter_column('contact_messages', 'subject',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('contact_messages', 'read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('images', 'blob_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('images', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_images_entity', table_name='images')
    op.drop_column('images', 'updated_at')
    op.alter_column('login_attempts', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('login_attempts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('projects', sa.Column('repo_url', sa.String(length=500), nullable=True))
    op.add_column('projects', sa.Column('published', sa.Boolean(), nullable=True))
    op.alter_column('projects', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('projects', 'technologies',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('projects', 'featured',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('projects', 'views',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_projects_featured'), 'projects', ['featured'], unique=False)
    op.create_index(op.f('ix_projects_published'), 'projects', ['published'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.drop_constraint('projects_author_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['author_id'], ['id'])
    op.drop_column('projects', 'github_url')
    op.drop_index('ix_reactions_entity', table_name='reactions')
    op.drop_index('ix_reactions_type', table_name='reactions')
    op.drop_constraint('uq_reaction_per_entity', 'reactions', type_='unique')
    op.create_unique_constraint('uix_reaction_user_entity', 'reactions', ['email', 'entity_id', 'entity_type'])
    op.alter_column('subscribers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('subscribers', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_subscribers_verification_token'), 'subscribers', ['verification_token'], unique=False)
    op.alter_column('two_factor_codes', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('two_factor_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'email_2fa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'totp_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'totp_secret',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('videos', 'source',
               existing_type=postgresql.ENUM('YOUTUBE', 'BLOB_STORAGE', name='videosourceenum'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('videos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_videos_blog_post_id'), 'videos', ['blog_post_id'], unique=False)
    op.create_index(op.f('ix_videos_project_id'), 'videos', ['project_id'], unique=False)
    op.drop_constraint('videos_project_id_fkey', 'videos', type_='foreignkey')
    op.drop_constraint('videos_blog_post_id_fkey', 'videos', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('videos_blog_post_id_fkey', 'videos', 'blog_posts', ['blog_post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('videos_project_id_fkey', 'videos', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_videos_project_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_blog_post_id'), table_name='videos')
    op.alter_column('videos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('videos', 'source',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('YOUTUBE', 'BLOB_STORAGE', name='videosourceenum'),
               existing_nullable=False)
    op.alter_column('users', 'totp_secret',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('users', 'totp_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'email_2fa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('two_factor_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('two_factor_codes', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_subscribers_verification_token'), table_name='subscribers')
    op.alter_column('subscribers', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('subscribers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint('uix_reaction_user_entity', 'reactions', type_='unique')
    op.create_unique_constraint('uq_reaction_per_entity', 'reactions', ['email', 'entity_id', 'entity_type'])
    op.create_index('ix_reactions_type', 'reactions', ['entity_id', 'entity_type', 'reaction_type'], unique=False)
    op.create_index('ix_reactions_entity', 'reactions', ['entity_id', 'entity_type'], unique=False)
    op.add_column('projects', sa.Column('github_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_author_id_fkey', 'projects', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_published'), table_name='projects')
    op.drop_index(op.f('ix_projects_featured'), table_name='projects')
    op.alter_column('projects', 'views',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projects', 'featured',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('projects', 'technologies',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('projects', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('projects', 'published')
    op.drop_column('projects', 'repo_url')
    op.alter_column('login_attempts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('login_attempts', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('images', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index('ix_images_entity', 'images', ['entity_id', 'entity_type'], unique=False)
    op.alter_column('images', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('images', 'blob_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('contact_messages', 'read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('contact_messages', 'subject',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('blog_posts', sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'blog_posts', type_='foreignkey')
    op.create_foreign_key('blog_posts_author_id_fkey', 'blog_posts', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_blog_posts_title'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_published'), table_name='blog_posts')
    op.alter_column('blog_posts', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('blog_posts', 'views',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('blog_posts', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('blog_posts', 'tags',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
